upgrade ndk to r10e

diff --git a/ndk-gdb b/ndk-gdb
--- a/ndk-gdb
+++ b/ndk-gdb
@@ -99,6 +99,7 @@ OPTION_LAUNCH=
 OPTION_LAUNCH_LIST=no
 OPTION_DELAY=
 OPTION_WAIT="-D"
+OPTION_PACKAGE_NAME=
 
 check_parameter ()
 {
@@ -262,6 +263,9 @@ while [ -n "$1" ]; do
             JDB_PORT=
             OPTION_WAIT=
             ;;
+        --package=*)
+            OPTION_PACKAGE_NAME="$optarg"
+            ;;
         -*) # unknown options
             echo "ERROR: Unknown option '$opt', use --help for list of valid ones."
             exit 1
@@ -305,6 +309,7 @@ if [ "$OPTION_HELP" = "yes" ] ; then
     echo "    --delay=<secs>    Delay in seconds between activity start and gdbserver attach."
     echo "    --project=<path>  Specify application project path"
     echo "    -p <path>         Same as --project=<path>"
+    echo "    --package=<name>  Specify package name"
     echo "    --port=<port>     Use tcp:localhost:<port> to communicate with gdbserver [$DEBUG_PORT]"
     echo "    --exec=<file>     Execute gdb initialization commands in <file> after connection"
     echo "    -x <file>         Same as --exec=<file>"
@@ -482,13 +487,18 @@ else
     log "Using auto-detected project path: $PROJECT"
 fi
 
-# Extract the package name from the manifest
-PACKAGE_NAME=`run_awk_manifest_script extract-package-name.awk`
-log "Found package name: $PACKAGE_NAME"
-if [ $? != 0 -o "$PACKAGE_NAME" = "<none>" ] ; then
-    echo "ERROR: Could not extract package name from $PROJECT/$MANIFEST."
-    echo "       Please check that the file is well-formed!"
-    exit 1
+if [ ! -z "$OPTION_PACKAGE_NAME" ]; then
+    PACKAGE_NAME="$OPTION_PACKAGE_NAME"
+    log "Using package name: $PACKAGE_NAME"
+else
+    # Extract the package name from the manifest
+    PACKAGE_NAME=`run_awk_manifest_script extract-package-name.awk`
+    if [ $? != 0 -o "$PACKAGE_NAME" = "<none>" ] ; then
+        echo "ERROR: Could not extract package name from $PROJECT/$MANIFEST."
+        echo "       Please check that the file is well-formed!"
+        exit 1
+    fi
+    log "Found package name: $PACKAGE_NAME"
 fi
 
 # If --launch-list is used, list all launchable activities, and be done with it
@@ -539,13 +549,23 @@ fi
 # And check that they are supported by the application
 #
 COMPAT_ABI=none
-adb_var_shell CPU_ABI1 getprop ro.product.cpu.abi
-adb_var_shell CPU_ABI2 getprop ro.product.cpu.abi2
 
-# Both CPU_ABI1 and CPU_ABI2 may contain multiple comma-delimited abis.
-# Concatanate CPU_ABI1 and CPU_ABI2 and replace all ',' with space.
-# Add trailing space to ease whole-word matching of APP_ABI.
-CPU_ABIS="$CPU_ABI1,$CPU_ABI2"
+# All modern Android images must support ro.product.cpu.abilist32
+# and ro.product.cpu.abilist64. Otherwise fall back to obsolete
+# ro.product.cpu.abi and ro.product.cpu.abi2
+adb_var_shell CPU_ABILIST64 getprop ro.product.cpu.abilist64
+adb_var_shell CPU_ABILIST32 getprop ro.product.cpu.abilist32
+CPU_ABIS="$CPU_ABILIST64,$CPU_ABILIST32"
+if [ -z "$CPU_ABILIST64" ] && [ -z "$CPU_ABILIST32" ] ; then
+    adb_var_shell CPU_ABI1 getprop ro.product.cpu.abi
+    adb_var_shell CPU_ABI2 getprop ro.product.cpu.abi2
+    CPU_ABIS="$CPU_ABI1,$CPU_ABI2"
+fi
+
+# Replace all ',' with space and add trailing space to
+# ease whole-word matching of APP_ABI
+CPU_ABILIST64=$(echo $CPU_ABILIST64 | tr ',' ' ')
+CPU_ABILIST32=$(echo $CPU_ABILIST32 | tr ',' ' ')
 CPU_ABIS=$(echo $CPU_ABIS | tr ',' ' ')
 log "Device CPU ABIs: $CPU_ABIS"
 
@@ -555,13 +575,38 @@ adb_var_shell BCFILES run-as $PACKAGE_NAME /system/bin/sh -c "ls lib/*.bc"
 if [ $? = 0 ]; then
     COMPAT_ABI="$UNKNOWN_ABI"
 else
-    for CPU_ABI in $CPU_ABIS; do
-        if [ "$APP_ABIS" != "${APP_ABIS%$CPU_ABI *}" ] ; then
-            COMPAT_ABI=$CPU_ABI
-            break
-        fi
-    done
+    # Assume that compatible ABI is 32-bit
+    COMPAT_ABI_BITS=32
+    # First look compatible ABI in the list of 64-bit ABIs
+    if [ -n "$CPU_ABILIST64" ] ; then
+        for CPU_ABI64 in $CPU_ABILIST64; do
+            if [ "$APP_ABIS" != "${APP_ABIS%$CPU_ABI64 *}" ] ; then
+                COMPAT_ABI=$CPU_ABI64
+                COMPAT_ABI_BITS=64
+                break
+            fi
+        done
+    fi
+    # If we found nothing - look among 32-bit ABIs
+    if [ "$COMPAT_ABI" = none ] && [ -n "$CPU_ABILIST32" ] ; then
+        for CPU_ABI32 in $CPU_ABILIST32; do
+            if [ "$APP_ABIS" != "${APP_ABIS%$CPU_ABI32 *}" ] ; then
+                COMPAT_ABI=$CPU_ABI32
+                break
+            fi
+        done
+    fi
+    # Lastly, lets check ro.product.cpu.abi and ro.product.cpu.abi2
+    if [ "$COMPAT_ABI" = none ] && [ -z "$CPU_ABILIST64" ] && [ -z "$CPU_ABILIST32" ]; then
+        for CPU_ABI in $CPU_ABIS; do
+            if [ "$APP_ABIS" != "${APP_ABIS%$CPU_ABI *}" ] ; then
+                COMPAT_ABI=$CPU_ABI
+                break
+            fi
+        done
+    fi
 fi
+
 if [ "$COMPAT_ABI" = none ] ; then
     echo "ERROR: The device does not support the application's targetted CPU ABIs!"
     echo "       Device supports:  $CPU_ABIS"
@@ -588,8 +633,9 @@ log "Using app out directory: $APP_OUT"
 
 # Check that the application is debuggable, or nothing will work
 DEBUGGABLE=`run_awk_manifest_script extract-debuggable.awk`
+RET=$?
 log "Found debuggable flag: $DEBUGGABLE"
-if [ $? != 0 -o "$DEBUGGABLE" != "true" ] ; then
+if [ "$RET" != 0 -o "$DEBUGGABLE" != "true" ] ; then
     # If gdb.setup exists, then we built with 'ndk-build NDK_DEBUG=1' and it's
     # ok to not have android:debuggable set to true in the original manifest.
     # However, if this is not the case, then complain!!
@@ -639,8 +685,8 @@ if [ $? != 0 ]; then
     TARGET_ARCH=none
 
     for ANDROID_ARCH in $ANDROID_NDK_ROOT/prebuilt/android-*; do
-        ANDROID_ARCH=${ANDROID_ARCH#*android-}
-        if [ x"$CPU_ABIS" != x"${CPU_ABIS#$ANDROID_ARCH*}" ]; then
+        ANDROID_ARCH=${ANDROID_ARCH#$ANDROID_NDK_ROOT/prebuilt/android-}
+        if [ "$COMPAT_ABI" = "$ANDROID_ARCH" ]; then
             TARGET_ARCH=$ANDROID_ARCH
             break;
         fi
@@ -685,7 +731,7 @@ fi
 
 if [ -n "$OPTION_LAUNCH" ] ; then
     log "Launching activity: $PACKAGE_NAME/$OPTION_LAUNCH"
-    run adb_cmd shell am start $OPTION_WAIT -n $PACKAGE_NAME/$OPTION_LAUNCH
+    adb_var_shell2 DUMMY am start $OPTION_WAIT -n $PACKAGE_NAME/$OPTION_LAUNCH
     if [ $? != 0 ] ; then
         echo "ERROR: Could not launch specified activity: $OPTION_LAUNCH"
         echo "       Use --launch-list to dump a list of valid values."
@@ -698,8 +744,9 @@ fi
 
 # Find the PID of the application being run
 PID=$(get_pid_of "$PACKAGE_NAME")
+RET=$?
 log "Found running PID: $PID"
-if [ $? != 0 -o "$PID" = "0" ] ; then
+if [ "$RET" != 0 -o "$PID" = "0" ] ; then
     echo "ERROR: Could not extract PID of application on device/emulator."
     if [ -n "$OPTION_LAUNCH" ] ; then
         echo "       Weird, this probably means one of these:"
@@ -728,7 +775,7 @@ fi
 
 # Launch gdbserver now
 DEBUG_SOCKET=debug-socket
-run adb_cmd shell run-as $PACKAGE_NAME $DEVICE_GDBSERVER +$DEBUG_SOCKET --attach $PID &
+adb_var_shell2 DUMMY run-as $PACKAGE_NAME $DEVICE_GDBSERVER +$DEBUG_SOCKET --attach $PID &
 if [ $? != 0 ] ; then
     echo "ERROR: Could not launch gdbserver on the device?"
     exit 1
@@ -744,16 +791,34 @@ if [ $? != 0 ] ; then
     exit 1
 fi
 
+# If we are debugging 64-bit app, then we need to pull linker64,
+# app_process64 and libc.so from lib64 directory
+LINKER_NAME=linker
+LIBDIR_NAME=lib
+APP_PROCESS_NAME=app_process32
+if [ "$COMPAT_ABI_BITS" = 64 ] ; then
+    LINKER_NAME=linker64
+    LIBDIR_NAME=lib64
+    APP_PROCESS_NAME=app_process64
+else
+    # Old 32-bit devices do not have app_process32. Pull
+    # app_process in this case
+    adb_var_shell2 DUMMY test -e /system/bin/$APP_PROCESS_NAME
+    if [ $? != 0 ] ; then
+        APP_PROCESS_NAME=app_process
+    fi
+fi
+
 # Get the app_server binary from the device
 APP_PROCESS=$APP_OUT/app_process
-run adb_cmd pull /system/bin/app_process `native_path $APP_PROCESS`
-log "Pulled app_process from device/emulator."
+run adb_cmd pull /system/bin/$APP_PROCESS_NAME `native_path $APP_PROCESS`
+log "Pulled $APP_PROCESS_NAME from device/emulator."
 
-run adb_cmd pull /system/bin/linker `native_path $APP_OUT/linker`
-log "Pulled linker from device/emulator."
+run adb_cmd pull /system/bin/$LINKER_NAME `native_path $APP_OUT/$LINKER_NAME`
+log "Pulled $LINKER_NAME from device/emulator."
 
-run adb_cmd pull /system/lib/libc.so `native_path $APP_OUT/libc.so`
-log "Pulled libc.so from device/emulator."
+run adb_cmd pull /system/$LIBDIR_NAME/libc.so `native_path $APP_OUT/libc.so`
+log "Pulled /system/$LIBDIR_NAME/libc.so from device/emulator."
 
 # Setup JDB connection, for --start or --launch
 if [ "$OPTION_START" = "yes" ] || [ -n "$OPTION_LAUNCH" ] ; then
